name: Evelyn Powers
favicon: null
layout_spectrum: 0.24882420059293509
typography_spectrum: 0.2820471259765327
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f25822'
    - '#ffffff'
    - '#fbd0bf'
    - '#f6906a'
    - '#f03f02'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
